import './globals.css'

import localFont from 'next/font/local'

// const favorit = localFont({
//   src: [
//     {
//       path: '../public/fonts/favorit-std-light.woff',
//       style: 'normal'
//     },
//     {
//       path: '../public/fonts/favorit-std-extended-light.woff',
//       style: 'extended'
//     }
//   ],
//   variable: '--font-favorit'
// })

const favorit = localFont({
  src: '../public/fonts/favorit-std-light.woff',
  variable: '--font-favorit'
})

const favoritExtended = localFont({
  src: '../public/fonts/favorit-std-extended-light.woff',
  variable: '--font-favorit-extended'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${favorit.className} ${favoritExtended.className}`}>{children}</body>
    </html>
  )
}
