import './globals.css'

import localFont from 'next/font/local'

const favorit = localFont({
  src: '../public/fonts/favorit-std-light.woff',
  variable: '--font-favorit'
})

const favoritExtended = localFont({
  src: '../public/fonts/favorit-std-extended-light.woff',
  variable: '--font-favorit-extended'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`grid grid-cols-4 md:grid-cols-12 gap-2.5 md:gap-15 lg:gap-5 mx-2.5 md:mx-15 lg:mx-5 ${favorit.variable} ${favoritExtended.variable}`}>{children}</body>
    </html>
  )
}
